// <auto-generated />
using BlazLinuxHostingAdmin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazLinuxHostingAdmin.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260626144649_InitMainDb")]
    partial class InitMainDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazLinuxHostingAdmin.Models.Dbases.TheDemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int")
                        .HasColumnName("birth_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_the_demo");

                    b.ToTable("the_demo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
